### ISSUE TITLE
grunt-protractor-webdriver does not work with selenium-server-standalone-2.47.1 

### ISSUE THREAD

**Issue by blabno** [seckardt/grunt-protractor-webdriver#17] opened 2015-09-29 09:32 UTC
The output of selenium-server-standalone-2.47.1 is different then selenium-server-standalone-2.45.0 and thus grunt plugin hangs. Last message is

    Starting Selenium server

**Comment by angelblade27** [comment] 2015-10-02 05:54
Getting the same issue as well

**Comment by blabno** [comment] 2015-10-02 06:21
@seckardt could you merge this one? It's one liner.

**Comment by xjie11** [comment] 2015-10-02 06:28
Thank you

**Comment by michael-rohac** [comment] 2015-10-02 06:31
I have same issue and found the root cause. In protractor_webdriver task, are declared regexps used to test incoming traffic from selenium. There's a REGEXP_START_READY which is tested against data responses and in case of match it calls function started(callback) which indicates that selenium is already started and protractor_webdriver async task is finished. Unfortunately seems that responses from selenium has been chaned in version 2.47.1 and thus async webdriver task is never ended. That's why neither protractor nor else grunt task after protractor_webdriver will ever run.

There are 2 workarounds, someone should fix the regexp or you can run grunt twice, first webdriver, secondly the rest of grunt tasks which should follow it For me worked when set regexp to this:

REGEXP_START_RUNNING = /Selenium is already running/

**Comment by blabno** [comment] 2015-10-02 06:39
@michael-rohac PR is waiting for 3 days now. https://github.com/blabno/grunt-protractor-webdriver/issues/1

**Comment by michael-rohac** [comment] 2015-10-02 06:41
Sorry, I'm quite new here and missed that PR is already created.

**Comment by xjie11** [comment] 2015-10-02 06:41
@blabno isn't that a pull request to your own fork? or does that show up for @seckardt

**Comment by blabno** [comment] 2015-10-02 06:50
@xjie11 damn, thanks, i've created a new one: https://github.com/seckardt/grunt-protractor-webdriver/pull/18

**Comment by xjie11** [comment] 2015-10-02 06:53
@blabno no problem and I hope the pull request goes through soon :)

**Comment by seckardt** [comment] 2015-10-02 06:58
Fixed with #18

**Closed by seckardt** 2015-10-02 06:58 UTC

**Comment by keirlawson** [comment] 2015-10-02 14:00
Any chance of a release containing this fix?

**Comment by angelblade27** [comment] 2015-10-02 14:03
+1 it would avoid me having to fork it
